# Generated by Django 5.1.4 on 2024-12-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfiles',
            name='processed_file',
            field=models.FileField(upload_to='processed_files/'),
        ),
        migrations.AlterField(
            model_name='unprocessedfiles',
            name='unprocessed_file',
            field=models.FileField(upload_to='unprocessed_files/'),
        ),
    ]
