# Generated by Django 5.1.4 on 2024-12-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_processedfiles_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfiles',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='unprocessedfiles',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
