# Generated by Django 5.1.4 on 2024-12-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_processedfiles_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfiles',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='unprocessedfiles',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
