# Generated by Django 5.1.4 on 2024-12-12 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_processedfiles_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unprocessedfiles',
            name='uploaded_by',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_file', models.FileField(upload_to='processed_files/')),
                ('filename', models.CharField(blank=True, max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('dept_approved', models.BooleanField(default=None)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessedFiles',
        ),
        migrations.DeleteModel(
            name='UnProcessedFiles',
        ),
    ]
