# Generated by Django 5.1.4 on 2024-12-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_unprocessedfiles_uploaded_by_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='dept_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
