# Generated by Django 5.1.4 on 2024-12-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_files_dept_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
