# Generated by Django 5.1.4 on 2025-08-22 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_files_dept_approved_by_alter_files_uploaded_by'),
        ('users', '0002_agency_district_zone_remove_user_office_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtOrderRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, unique=True)),
                ('submitted', models.BooleanField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, unique=True)),
                ('submitted', models.BooleanField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanOrderRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, unique=True)),
                ('submitted', models.BooleanField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoOrderRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, unique=True)),
                ('submitted', models.BooleanField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MTPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, unique=True)),
                ('submitted', models.BooleanField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('document_type', models.CharField(blank=True, max_length=5, null=True)),
                ('index_type', models.CharField(blank=True, max_length=5, null=True)),
                ('received', models.IntegerField(blank=True, null=True)),
                ('uploaded', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegularDocumentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, unique=True)),
                ('submitted', models.BooleanField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RHRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, unique=True)),
                ('submitted', models.BooleanField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='admin_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='files',
            name='dept_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='digr_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='digr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='digr_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digr_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='files',
            name='district_rgtr_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='district_rgtr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='district_rgtr_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_rgtr_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='files',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.office'),
        ),
        migrations.AddField(
            model_name='files',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='remark_by_scanner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='send_to_qc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='files',
            name='send_to_sro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='files',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['uploaded_at'], name='documents_f_uploade_98a2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['office'], name='documents_f_office__97b137_idx'),
        ),
        migrations.AddField(
            model_name='receiveddocuments',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.agency'),
        ),
        migrations.AddField(
            model_name='receiveddocuments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
